version: '3.8'

services:

  # Ollama VLM Server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    # Optional: Uncomment the 'deploy' section if you have an NVIDIA GPU to speed up VLM inference
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  # Streamlit Web GUI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    networks:
      - default

volumes:
  ollama_data:
